### ISSUE TITLE
Demo pictures not loading

### ISSUE THREAD

**Issue by dhstack** [TryGhost/Massively#10]
On the demo site (https://massively.ghost.io/elements/), the images don't load on the elements page.

They seem to have the wrong path setup. I looked in the code and couldn't find the page, so I assume it's in the ghost admin where the content is (custom html block?).

Anyway, all that needs to be done is add `/assets/` before each of the image paths.

![image](https://user-images.githubusercontent.com/2013388/60615498-4126d100-9d9d-11e9-937f-2229b4830bf8.png)

The original has it showing up correctly: https://html5up.net/uploads/demos/massively/elements.html

**Comment by daviddarnes** [comment]
Thanks for pointing this out @dhstack. I've updated the paths and the images are there now 👍

**Comment by dhstack** [comment]
@daviddarnes Looks like they all work except the right align one. That path still needs to be updated.

![image](https://user-images.githubusercontent.com/2013388/60736946-e0c39b00-9f26-11e9-913c-20f897560b94.png)

**Comment by daviddarnes** [comment]
Oops, thanks @dhstack. I think I've sorted it now
