### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by Wittionary** [TryGhost/Massively#106]
Version 1.0.3 was released in 2020. Since then, numerous updates and improvement have been made to the repo to account for Ghost releases. I think a new release is warranted to signify the changes and provide a packaged download for users seeking to update their current install of Massively that broke with an update (like mine did).
For example, I just installed my 3rd iteration of the 1.0.3 release, but each install fixed an issue I was having with my blog.

**Comment by HLFH** [comment]
I am not able to make it work on the latest Ghost release. I am now switching to the compatible Edition theme that looks similar: https://github.com/TryGhost/Edition

**Comment by minimaluminium** [comment]
Hey everyone, there's a new release now https://github.com/TryGhost/Massively/releases/tag/v1.1.0
