### ISSUE TITLE
Massively 1.0.2 reports as 1.0.1 in the Ghost admin Design interface

### ISSUE THREAD

**Issue by taw00** [TryGhost/Massively#11]
SSIA

Install 1.0.2... Look in your Ghost admin interface and it lists it as version 1.0.1

**Comment by daviddarnes** [comment]
Massively is at 1.0.1 https://github.com/TryGhost/Massively/blob/master/package.json#L5, where are you seeing 1.0.2?

**Comment by kevinansfield** [comment]
@daviddarnes here https://github.com/TryGhost/Massively/releases. Looks like the bump in package.json was missed, I expect it will need to be bumped to 1.0.3 and a new tag+release created
