### ISSUE TITLE
How to print tags on page in this themes

### ISSUE THREAD

**Issue by aaryabhatt** [TryGhost/Massively#38]
Hi Team,

I am new to ghost and used this massively theme version 1.0.1. It is hosted on Ubuntu 18.04 VM. I want to do two things in this theme. 
1. To print all tags in a page 
2. to add share icon of linked on each blog post. 

Let me know, how can I do this.

--
BR

Amit Bondwal

**Comment by matthanley** [comment]
Hey @aaryabhatt  👋 We ask that you please do not use GitHub for help or support 😄. We use GitHub solely for bug-tracking and on-going feature development.

Many questions can be answered by reviewing our documentation. If you can't find an answer then our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
