### ISSUE TITLE
background is shaky while scrolling in firefox

### ISSUE THREAD

**Issue by jeyca** [TryGhost/Massively#39]
using firefox 68.9.0esr makes problems with the background image, its most of the time shaking very much while scrolling down and up. Problem does not appear in google chrome.

**Comment by minimaluminium** [comment]
Fixed in https://github.com/TryGhost/Massively/commit/cb803d430bba41af565fdd3041f4bae53a0d8370.

**Comment by minimaluminium** [comment]
[▶️ Here is](https://youtu.be/QEk0IeTC2gY) a comparison of the scroll performance before and after the fix.
