### ISSUE TITLE
Subscribe feature not working

### ISSUE THREAD

**Issue by LukeFerris** [TryGhost/Massively#45]
Thanks for this template - it's great.

I've just noticed on turning on the members feature in the labs section of Ghost that the bottom of the page subscribe feature doesn't seem to be appearing. I note in the code that it is meant to.

Repro: Upload the template to Ghost, turn on the members feature in labs and refresh the live site.

**Comment by minimaluminium** [comment]
Hey @LukeFerris, the subscribers feature implemented in Massively was an experimental feature and has now been deprecated by [Members](https://ghost.org/docs/members/requirements/) feature. [Lyra](https://github.com/TryGhost/lyra) and [Pico](https://github.com/TryGhost/pico) are the themes which fully supports the Members feature at the moment.

**Comment by LukeFerris** [comment]
Perfect.. thanks for letting me know.

________________________________
