### ISSUE TITLE
Header Image resize options

### ISSUE THREAD

**Issue by Claywd** [TryGhost/Massively#63]
Howdy folks. It would be awesome if we could add the option to set a default Publication cover size for mobile. If you check out the website lakewoodestatestx.org on a web browser you get the big beautiful cover image but on a mobile device its totally overblown. 

In fact, if I could use the publication logo instead, that would also work.

**Comment by Claywd** [comment]
Oh, I'm also open to the idea of just editing my own massively template but I need a little guidance on where to change the setting so that the Publication cover size scales properly on mobile.

**Comment by minimaluminium** [comment]
Hey @Claywd, sorry about the delay! Here's how the theme's demo site looks on mobile screen.

![Screen Shot 2021-03-12 at 3 16 02 PM](https://user-images.githubusercontent.com/1418797/110905733-e8675400-8345-11eb-8b81-09c010c8413b.png)

If you want to use a different sized image for mobile (in case your image doesn't suit well depending on the context), you can always use CSS media query to set an image specifically for mobile screen sizes.

```css
@media (max-width: 600px) {
    #wrapper > .bg {
        background-image: url("IMAGE_URL_HERE");
    }
}
```
