### ISSUE TITLE
404 page does not reflect the changes made to default.hbs

### ISSUE THREAD

**Issue by kincsescsaba** [TryGhost/Massively#68]
Hi, As I see, the 404 page does not reflect the changes previously made to default.hbs (like modifying the copyright information), and I can't figure out which template to modify then. Also, it would be nice to have such content at the same place so that I won't need to rewrite it twice in case of need for any update

**Comment by minimaluminium** [comment]
Hi there, you're right! I've just moved the copyright elements to a separate partial `/partials/copyright.hbs` in https://github.com/TryGhost/Massively/commit/862f4d840ebaa7957af8369d786d3c319d5e5f7b. Now you can update only this file, and the changes will be visible everywhere.
