### ISSUE TITLE
No secondary menu

### ISSUE THREAD

**Issue by kincsescsaba** [TryGhost/Massively#69]
Hi, Ghost let's to configure a secondary menu but I don't see this in the theme. Is there any existing / recommended way to activate such a thing?

**Comment by minimaluminium** [comment]
Hi @kincsescsaba, you can use `{{navigation type="secondary"}}` helper anywhere you like to display. For example, [here's](https://github.com/TryGhost/Casper/blob/85cd131cf1afb74c14543b5e370064205148731e/default.hbs#L73) how it's been used in Casper.
