### ISSUE TITLE
How can I add auto-darkmode

### ISSUE THREAD

**Issue by blacktop** [TryGhost/Massively#84]
Similar to how Casper can detect the macOS theme and match it?

**Comment by minimaluminium** [comment]
Hey 👋 . We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
